### ISSUE TITLE
add new network interfaces

### ISSUE THREAD

**Issue by gruen66** [bandesz/AirConnect-Synology#1]
Ifconfig on a ds216play list‘s eth0 as standard interface

in my opinion the right way is to edit the start-stop-status-script (see folder srcipts). 
the script is located in /var/packages/AirConnect/scripts/

we have to change the following line:

sudo vi /var/packages/AirConnect/scripts/start-stop-status
change
IP=$(/sbin/ifconfig **lbr0** | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
to
IP=$(/sbin/ifconfig **eth0** | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')

now airconnect can be started via package center....

**Comment by Gatschi** [comment]
Me too: ds214play eth0

**Comment by bandesz** [comment]
@gruen66 @Gatschi I'm closing this issue. Please open a new one if you encounter further issues.
