### ISSUE TITLE
Cannot start because "adding renderer" is not found in log file

### ISSUE THREAD

**Issue by h4de5** [bandesz/AirConnect-Synology#10]
Hi,

[checking only the last 3 lines](https://github.com/bandesz/AirConnect-Synology/blob/b3f930574b11cd5abfa13555fe33a012405a4fa3/scripts/start-stop-status#L18) in the log file, seems to be too less. here is an example from my network:

> [01:16:09.868332] Start:965 Binding to 192.168.*.*:49154
> [01:16:09.993669] AddMRDevice:878 [0x697a40]: adding renderer (Name (DLNA))
> [01:16:09.993785] AddMRDevice:892 [0x697a40]: cannot get mac Name (DLNA)+, creating fake 4e7****
> [01:16:10.004819] AddMRDevice:878 [0x6995c8]: adding renderer (Name2 (DLNA))
> [01:16:10.004969] AddMRDevice:892 [0x6995c8]: cannot get mac Name2 (DLNA)+, creating fake 264****
> [01:16:10.018680] MasterHandler:587 [0x697a40]: subscribe success
> [01:16:10.023136] MasterHandler:587 [0x6995c8]: subscribe success

there are renderers found by airconnect, but the start-stop script kills the process right away due to the limited search.

Version: 2.0.5
DSM 6.1.6 (stable)
Render Chromecast2, Chromecast Audio

**Comment by bandesz** [comment]
Hi @h4de5, you misread the code. The code checks the whole file three times max, waiting one second between the tries. Is this the whole log file?

**Comment by h4de5** [comment]
@bandesz : oh. I am sorry. I changed it to 5 and it worked - so I thought it was the number of lines. It must be the increasing sleep commando that helped.

**Comment by bandesz** [comment]
@h4de5 I updated the timeout to 5 seconds.
