### ISSUE TITLE
Error while loading shared libraries: libcypto.so.1.0.0

### ISSUE THREAD

**Issue by schmudi** [bandesz/AirConnect-Synology#11]
Hi,

read about AirConnect in Caschys Blog and wanted to try it right away.
Installed the version AirConnect-x86-0.2.0.5-20180330.spk for a Synology DS412+. Installation went smoothly, but starting of the package is not possible.

Log:
/var/packages/AirConnect/target/airupnp: error loading shared libraries: lib crypto.so.1.0.0: cannot open shared object file: No such file or directory

Regards,
schmudi

**Comment by bandesz** [comment]
Hi @schmudi, sorry, but I can't help as I only made the Synology package. Please try to get help in the original project: https://github.com/philippe44/AirConnect.
