### ISSUE TITLE
Failed to start airupnp on any of the local interfaces

### ISSUE THREAD

**Issue by webexplored** [bandesz/AirConnect-Synology#12]
Hi,

installed AirConnect-x86-64-0.2.0.5-20180330.spk on my DS216+II. Everything was smooth but the package can not be started and the log says: "AirConnect: Failed to start airupnp on any of the local interfaces, please make sure you have at least one UPnP/Sonos device on your network".

I have two Sonos Play 1 on my local network, one on 192.168.178.5 and the other on 192.168.178.7.

Don't get where the problem is.

**Comment by bandesz** [comment]
@webexplored could you paste the logs when you don't set the IP? Also when you set the IP you should set it the router's IP. You can find it by running `ifconfig -a | grep -E -B 1 "inet addr:(10|192)\\."` and get the right 192.* IP.

**Comment by webexplored** [comment]
That's what I see in the log file when I set the IP to the router's IP:

![image](https://user-images.githubusercontent.com/38406356/38796382-903fecf8-415b-11e8-817b-23c7f78e3173.png)

**Comment by webexplored** [comment]
and that's what I get without setting any IP:

![image](https://user-images.githubusercontent.com/38406356/38796550-01520dae-415c-11e8-8fc0-c275f9822879.png)

192.168.178.33 is the IP address of my Synology.

**Comment by webexplored** [comment]
@bandesz I'd love to hear any feedback from you... thanks

**Comment by D4rkiii** [comment]
Hey i got the same problem and i am not very skilled in linux to build my own package with my hardcoded internal ip. 
My Sonos has the ip 192.168.1.35 and upnp / mediaserver options are both on.

**Comment by bandesz** [comment]
@webexplored I changed the timeout to 5 seconds in the start script as it might cause an early shutdown - it might solve your issue.

If not then I suggest to SSH into your DS and run the airconnect process manually until you find the right configuration. You can find the package files in /var/packages/AirConnect/target

**Comment by bandesz** [comment]
@D4rkiii I'm not sure how strict your firewall rules are but I didn't have to set anything extra on my Synology router's firewall

**Comment by D4rkiii** [comment]
@bandesz i blocked all ports, except the ports i need for the applications.

**Comment by webexplored** [comment]
@bandesz still out of luck, but the proposed solution from @D4rkiii worked for me. Great thanks to both of you!
