### ISSUE TITLE
Airplay 2

### ISSUE THREAD

**Issue by ACIDHE4D** [bandesz/AirConnect-Synology#18]
Hello,

I am a fan of your implementation for the Synology. But there is one Problem. The Sonos Play 1 is not supported for the use of Airplay 2 in the new sonos update and I have a lot of them. Do you plan to implement Airplay 2 into AirConnect?

Kind Regards,
ACIDHE4D

**Comment by bandesz** [comment]
@ACIDHE4D This is a question for the original developer and there is already an open issue about it: https://github.com/philippe44/AirConnect/issues/97
