### ISSUE TITLE
Package is not supported or is imcompatible

### ISSUE THREAD

**Issue by ejel** [bandesz/AirConnect-Synology#19]
Trying the manually install the package I get the following error message:

> This package is not supported on the platform of DiskStation or is incompatible with the current DSM version

I'm running DSM 6.2 on DS216 which is supposed to be a support architecture (ARMv7). Do you have any idea on the cause of the error?

**Comment by yuppjo** [comment]
I get the same error message:

DSM 6.2-23739 Update 2 on DS218play
Processor: Realtek RTD1296 SoC

Is there any opportunity for manual install?

Hopefully...

**Comment by bandesz** [comment]
@ejel it seems there are some version of DS216 with intel CPU-s, could you please try first the intel 64bit package and the 32bit package?

@yuppjo yours seems to be using an ARMv8 and it wasn't in the supported arch list. I've added it in the latest release, but I have no idea if it will work. Please give it a try.

**Comment by yuppjo** [comment]
> @yuppjo yours seems to be using an ARMv8 and it wasn't in the supported arch list. I've added it in the latest release, but I have no idea if it will work. Please give it a try.

Thank you - so good to here from you bandesz! 
Installation works! 
But when I try to run the package service i get "Failed to run the package service". 
Any idea what I can do?

**Comment by bandesz** [comment]
@yuppjo from the Package Center please paste the logs from "View log". There is a possibility the binaries don't work on ARMv8.

**Comment by bandesz** [comment]
@yuppjo I only have a Synology Router, and the Package Center might be different than yours, but you should click Installed, then click on the AirConnect package and on the package page there should be a View log link (you might have to scroll down a little).

**Comment by yuppjo** [comment]
@bandesz FYI: I have a FRITZ!Box 7360 Router. 
I installed the package over the "Package Center" of my DiskStation Manager (DSM 6.2-23739 Update 2). No "View Log"-possibility there... sorry.

![image](https://user-images.githubusercontent.com/42234910/46411376-ebdd6680-c71b-11e8-9c7d-93c5a5096700.png)

**Comment by bandesz** [comment]
@yuppjo I see all the log management was moved to the Log Center app. Sadly I can't install it, so your only chance could be to SSH to your router and check for the logs on the filesystem: /tmp/airconnect.log.

**Comment by yuppjo** [comment]
@bandesz Does this help?

2018-10-03T16:56:15+02:00 JMWC-Server synoscgi_SYNO.Core.Package.Control_1_start[16037]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-AirConnect][0xD900 manager.cpp:204]
2018-10-03T16:56:15+02:00 JMWC-Server [  982.722726] init: pkgctl-AirConnect pre-start process (16614) terminated with status 1
2018-10-03T16:56:15+02:00 JMWC-Server [  983.024042] init: pkgctl-AirConnect post-stop process (16678) terminated with status 1
2018-10-03T16:56:16+02:00 JMWC-Server synoscgi_SYNO.Core.Package.Control_1_start[16037]: service_initjob_action.c:27 InitJobStart failed, [0xD900 manager.cpp:204]
2018-10-03T16:56:16+02:00 JMWC-Server synoscgi_SYNO.Core.Package.Control_1_start[16037]: pkgstartstop.cpp:379 Failed to start pkgctl-AirConnect (err=-1) [0xD900 manager.cpp:204]

**Comment by bandesz** [comment]
@yuppjo sadly no. Without debugging it locally on the device it's hard to say.

**Comment by benk112** [comment]
Hello.
i´m running an ds418 and i have the same problem.
i have installed the .spk file for the rtd1296.
it installed normally. i got the same error: failed to run the package service.
i have tryed to search in the log files, but i cant open them. it shows me, that it got installed properly.

i also don´t understand what to do with the rest of the files. do i need to copy the files of the .zip file on the nas?

i also changed the commented lines # about the fixed ip adress.

i don´t know how to deal with it.

pls help me. =)

**Comment by hacky98** [comment]
Same problem here.
DS218play,  rtd1296
I get the message: failed to run the package service.
The ssh Command says "-sh: airupnp: command not found"

**Comment by bandesz** [comment]
@benk112 @hacky98 sorry, but I can't really do anything about these issues without being able to debug on these devices.
