### ISSUE TITLE
Failed to get IP address from lbr0 interface - libcrypto.so.1.0.0 not available

### ISSUE THREAD

**Issue by noestreich** [bandesz/AirConnect-Synology#2]
For historic reasons i only use the second LAN-Interface on my Diskstation. LAN 1 has no wired ethernet-connection. 

After trying to run the AirConnect-Package, synology throws the following error: "Failed to get IP address from lbr0 interface".

**Comment by noestreich** [comment]
Follow-Up: 
i just read through the "How it works"-part, sorry for the oversight. Since i got no lbr0 interface on my Diskstation, I edited the Interface to eth0 an rebuild the package. 
The make file throws the following error:

> cp LICENSE target/LICENSE
> cp: LICENSE: No such file or directory

After copying the license [from here](https://raw.githubusercontent.com/philippe44/AirConnect/master/LICENSE) by hand the build and install went fine, but the package would not start. The log shows the following error:

> /var/packages/AirConnect/target/airupnp: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by h4de5** [comment]
@bandesz just tried release 2.0.4 got this error:
![image](https://user-images.githubusercontent.com/6115324/36876704-88f16eea-1db6-11e8-968d-fe21f0b8a050.png)

could you please include another check for a bond network interface? 
looks similar to this:
> bond0     Link encap:Ethernet  HWaddr 00:11:22:33:44:55
>           inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0

**Comment by bandesz** [comment]
@h4de5 bond0 sorted and I updated the latest release packages.
