### ISSUE TITLE
Package icon not being used

### ISSUE THREAD

**Issue by gerstnr** [bandesz/AirConnect-Synology#20]
Hey bandesz,
my latest DSM shows the default icon for this package (ARM build) instead of the one in the repo.
Of course this does not really bother me, but it's a good excuse to open an issue and say: Thank you! ;-)
Cheers, gerstnr

PS: In case this is relevant for other users – I just got Airplay working with the Raumfeld Stereo L system via my ds213j.

**Comment by bandesz** [comment]
@gerstnr thank you, the package icon was fixed in the latest release.
