### ISSUE TITLE
Feature Request: Update function

### ISSUE THREAD

**Issue by heutger** [bandesz/AirConnect-Synology#22]
Hi,

is it possible to make third party Synology "apps" updatable without the new to install them on each update again?

Regards,
Christian

**Comment by bandesz** [comment]
@heutger possibly, by submitting this package to Synology to be included in the official package center. But as I'm not the creator of the original software nor do I own a DiskStation (I own a Synology router which doesn't use the same package center), I'm not going to bother with this. Sorry.
