### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by leroyrichjr** [bandesz/AirConnect-Synology#23]
Is there an option for a config file that we can edit?  I'd like to exclude some devices, as well as change the name of some others.  Thank you!

**Comment by bandesz** [comment]
@leroyrichjr currently there is no support for a config file although you can fork this project and with minimal modifications you can build your own package.

**Comment by gsi095** [comment]
is there any plan to follow the original and allow editing the config without modification?

**Comment by bandesz** [comment]
@gsi095 what do you mean by "allow editing the config without modification?"

**Comment by gsi095** [comment]
to edit the config file you mentioned you ned to modify the build and create your own package. If there any chance it will just be built in?

**Comment by bandesz** [comment]
@gsi095 not much, unless someone else does it and opens a pull request.
