### ISSUE TITLE
Thank you! ... and anything I can do about the latency?

### ISSUE THREAD

**Issue by othyn** [bandesz/AirConnect-Synology#5]
I know this isn't necessarily the appropriate place to say so, but really, thank you! This was completely painless to setup and use. I was going to break out the Pi, but now it resides on my media NAS, so thank you!

Confirmed working on a DS213J @ DSM 6.1.5, just as a note.

Well, actually, more appropriateIs there is a slight issue. Anything I can do about the latency, e.g. playing a YouTube video, it doesn't pause to sync the audio before continuing on. Any ideas?

**Comment by bandesz** [comment]
Hi @othyn, thanks, I appreciate it!

You should check out the following:
 - https://github.com/philippe44/AirConnect#config-file-parameters
 - https://github.com/philippe44/AirConnect#latency-parameters-explained

If you want you can build your own package following the instructions in this project's readme. E.g. you can try to remove the "-l 1000:2000" parameter from the scripts/start-stop-status script.

If you have problems with the build I can create a release with no latency in it for you to try.

**Comment by othyn** [comment]
Thank you!

Yeh tried a build with the latency removed, better - but still around 500ms delay - noticeable.

Looking online, it seems to be a common problem with the YouTube player. All other system level video playback via the AVKit framework Apple provides gets the latency accounted for by the video pausing until the buffer is built. YouTube do not accommodate for that and just power through it...

So no fix until YouTube build it in, either that or its third party app time!

Thank you anyway, the help was appreciated! 👍 :)
