### ISSUE TITLE
Another network interface

### ISSUE THREAD

**Issue by lewislin** [bandesz/AirConnect-Synology#6]
Hi Andras,

Thanks for creating the package. My NAS is using ovs_eth0 as the local network interface. I think it might be from the Virtual Machine Manager package that I installed. When you get a chance could you please add that into the start script?

Thank you,
Lewis

**Comment by bandesz** [comment]
Hi @lewislin,

I changed the start script to look up automatically the first 10.* or 192.168.* IP address.

You can find the latest packages under https://github.com/bandesz/AirConnect-Synology/releases.

Please let me know if this fixes your issue.

**Comment by lewislin** [comment]
Hi Andras,

Thank you for your prompt help. First, I figured out how I could build from your source code, so I was able to build a version for my need.

I did try your new version, but unfortunately, my system has a VPN interface that happens to start with 10.*. The new start script would use that instead of the correct 192.168.* IP. Now I am curious how other similar package request for the correct IP address as there might be so many variations. 

On another note, despite all these efforts, I think AirConnect does not work in my environment. Only got this in the log, but my iPhone can not see any AirPlay device.

[15:54:16.672909] main:1205 Starting airupnp version: v0.2.0.4 (Feb 18 2018 @ 18:11:46)
[15:54:16.771030] AddMRDevice:892 [0x697a40]: cannot get mac Living Room+, creating fake 229a8eb3

Thanks again for your help. I will try to figure out why AirConnect does not work.
Lewis

**Comment by bandesz** [comment]
I was afraid this might happen.
On my router I also have a VPN interface which starts with 10., but I have an other (lbr0) which I need and it is also a 10. one. For me it doesn't work with 192.168.*.

Could you please attach your interfaces?

```
ifconfig -a | grep -E -B 1 "inet addr:(10|192)\\."
```

For example I have these:
```
gbr0      Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx
          inet addr:192.168.2.1  Bcast:192.168.2.255  Mask:255.255.255.0
--
lbr0      Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx
          inet addr:10.1.14.1  Bcast:10.1.14.255  Mask:255.255.255.0
--
tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.27.10.6  P-t-P:10.27.10.5  Mask:255.255.255.255
```

Maybe if I also filter for only Ethernet interfaces I can exclude your VPN interface.

The airupnp logs you pasted look normal.

**Comment by bandesz** [comment]
For debugging this might help: https://github.com/bandesz/AirConnect-Synology/blob/master/README.md#debugging

**Comment by lewislin** [comment]
Thanks!
`ovs_eth0  Link encap:Ethernet  HWaddr 00:11:32:47:F0:A3  
          inet addr:192.168.16.5  Bcast:192.168.16.255  Mask:255.255.255.0
--
ovs_eth1  Link encap:Ethernet  HWaddr 00:11:32:47:F0:A4  
          inet addr:192.168.16.6  Bcast:192.168.16.255  Mask:255.255.255.0
--
tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.8.16.1  P-t-P:10.8.16.2  Mask:255.255.255.255
`

While I was looking for the issue. AirConnect 0.2.0.5 just come out.
Just curious where do I get the repo revision for the new version?

Cheers,
Lewis

**Comment by bandesz** [comment]
I get the last commit hash from here: https://github.com/philippe44/AirConnect/commits/master, e.g. currently it's `0ddfa6535a6d097fc7a22fee36a0c755d616fb44`. We have to use a hash as the original project doesn't have any tags.

**Comment by lewislin** [comment]
Got it. Thanks again!

**Comment by bandesz** [comment]
@lewislin I updated the start script to filter the Ethernet interfaces and also updated to 0.2.0.5.
I hope you managed to figure out why it wasn't working for you.

**Comment by lewislin** [comment]
Yes. Everything is working. Thank you!

**Comment by rizwank** [comment]
As a note for those who may need to force their own ip; you can also edit the sh at 
/var/packages/AirConnect/scripts
