### ISSUE TITLE
airconnect user?

### ISSUE THREAD

**Issue by PieterSten** [bandesz/AirConnect-Synology#8]
Hi,

I noticed that after installing the package there is an "airconnect" user added to the system. It seems that airupnp is running under this user.

Is there a specific reason for this? On my system it doesn't work stable and when I change the start-stop-status script to have it run as the default user it does work normally.

**Comment by bandesz** [comment]
Hi,

It's for security reasons so it doesn't run with the root user. Also every package should have it's own user and not use a common one.

What do you mean by the default user? What stability issues do you see, anything useful in the logs?

**Comment by PieterSten** [comment]
when running under the airconnect user it will start briefly and then stop again.

When I try to run the command manually in a terminal window I see the same:

`start-stop-status start`

The process runs for a little while and the stops. Nothing in the log file except:

[15:29:19] Starting airupnp

**Comment by PieterSten** [comment]
found it!

for some reasons this were the permissions on the log file:

-rw-r--r-- 1 root root 74600 Mar 27 15:29 /tmp/airupnp.log

I corrected it and it seems to work.

**Comment by bandesz** [comment]
@PieterSten the script changes the log file ownership, but my latest change might be doing something unexpected: https://github.com/bandesz/AirConnect-Synology/blob/edb6ecf0dcc9ba900fb53109d6c3ecc1fd7f6db3/scripts/start-stop-status#L32

I'll have a closer look at it soon.

**Comment by bandesz** [comment]
@PieterSten I changed how the logfile is created, please give it a try.
