### ISSUE TITLE
Noob help: how do I run this after clone?

### ISSUE THREAD

**Issue by ccboth** [bandesz/AirConnect-Synology#9]
Hello. I’m new to git and new to Sonos. I’d like to make this work. 
So far I’ve been able to successfully ssh into my Synology NAS and clone your package. ... now what? I’m not sure how to install it or run it successfully. Hopefully you don’t mind helping me out, or can point me in the right direction. Thanks.

**Comment by bandesz** [comment]
Hi @ccboth,

Normally you would pick an spk package file from [here](https://github.com/bandesz/AirConnect-Synology/releases/tag/v0.2.0.5), and install it through the Package Center.

If you already tried that but it failed to start please include the logs here (In the Package Center under the package there is a View log link).

You can find which build you need by reading the first paragraph from the readme.

**Comment by ccboth** [comment]
Hi @bandesz,

Thanks for the help! I was obviously overcomplicating this. It seems to be working great with the spk file.
Thank you!
